version: "3"

services:
  database:
    image: postgres:13-alpine
    container_name: shopping-list-grpc_database
    env_file:
      - ./.db.env
    ports:
      - 5432:5432
  
  backend:
    build: ./backend
    container_name: shopping-list-grpc_backend
    command: >
      sh -c "alembic upgrade head && 
             python src/server.py"
    env_file:
      - ./.dev.env
    volumes:
      - ./backend/:/usr/src/app/
      - ./proto/:/usr/src/app/proto/
    ports:
      - 50051:50051
    depends_on:
      - database
  
  envoy:
    image: envoyproxy/envoy-dev
    container_name: shopping-list-grpc_envoy
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - backend
  
  frontend:
    build: ./frontend
    container_name: shopping-list-grpc_frontend
    command: npm start
    volumes:
      - ./frontend/:/usr/src/app/
      - ./proto/:/usr/src/app/proto/
    ports:
      - 3000:3000