version: "3"

services:
  database:
    image: postgres:13-alpine
    container_name: contact-list_database
    env_file:
      - ./.db.env
    ports:
      - 5432:5432
  
  backend:
    build: ./backend
    container_name: contact-list_api
    command: >
      sh -c "alembic upgrade head && 
             uvicorn --host 0.0.0.0 --port 8000 --reload src.main:app"
    volumes:
      - ./backend/:/usr/src/app/
    env_file:
      - ./.dev.env
    ports:
      - 8000:8000
    depends_on:
      - database
  
  frontend:
    build: ./frontend
    container_name: contact-list_frontend
    command: npm start
    volumes:
      - ./frontend/:/usr/src/app/
      - /usr/src/app/node_modules/
    ports:
      - 3000:3000
    depends_on:
      - database