# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x07\n\x05\x45mpty\"z\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x30\n\x0c\x63reated_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tcompleted\x18\x05 \x01(\x08\")\n\x0bProductList\x12\x1a\n\x08products\x18\x01 \x03(\x0b\x32\x08.Product\"\x1f\n\x11ProductGetRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\"\n\x14ProductDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"F\n\x11ProductAddRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x11\n\tcompleted\x18\x03 \x01(\x08\"\x87\x01\n\x14ProductUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x30\n\x0c\x63reated_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tcompleted\x18\x05 \x01(\x08\x32\xdc\x01\n\x12ProductListService\x12 \n\x06GetAll\x12\x06.Empty\x1a\x0c.ProductList\"\x00\x12%\n\x03Get\x12\x12.ProductGetRequest\x1a\x08.Product\"\x00\x12%\n\x03\x41\x64\x64\x12\x12.ProductAddRequest\x1a\x08.Product\"\x00\x12+\n\x06Update\x12\x15.ProductUpdateRequest\x1a\x08.Product\"\x00\x12)\n\x06\x44\x65lete\x12\x15.ProductDeleteRequest\x1a\x06.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=51
  _EMPTY._serialized_end=58
  _PRODUCT._serialized_start=60
  _PRODUCT._serialized_end=182
  _PRODUCTLIST._serialized_start=184
  _PRODUCTLIST._serialized_end=225
  _PRODUCTGETREQUEST._serialized_start=227
  _PRODUCTGETREQUEST._serialized_end=258
  _PRODUCTDELETEREQUEST._serialized_start=260
  _PRODUCTDELETEREQUEST._serialized_end=294
  _PRODUCTADDREQUEST._serialized_start=296
  _PRODUCTADDREQUEST._serialized_end=366
  _PRODUCTUPDATEREQUEST._serialized_start=369
  _PRODUCTUPDATEREQUEST._serialized_end=504
  _PRODUCTLISTSERVICE._serialized_start=507
  _PRODUCTLISTSERVICE._serialized_end=727
# @@protoc_insertion_point(module_scope)
